/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentPanel: typeof import('./src/components/AgentPanel.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    ContractModule: typeof import('./src/components/ContractModule.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileTreeNode: typeof import('./src/components/FileTreeNode.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    QuickOpenModal: typeof import('./src/components/QuickOpenModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    TabSwitcherModal: typeof import('./src/components/TabSwitcherModal.vue')['default']
    TerminalPanel: typeof import('./src/components/TerminalPanel.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UIcon: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    WindowSwitcherModal: typeof import('./src/components/WindowSwitcherModal.vue')['default']
  }
}
